name: Tests
on: [push]
jobs:
  tests:
    name: test-ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.12
            3.11
            3.10
            3.9
      - run: npm install -g azurite
      - run: pip install hatch
      - run: hatch run test:pytest
